name: Build and Deploy Doxygen Documentation to Github Pages
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'include/*'
      - 'src/*'
      - '.github/workflows/build_and_deploy_docs.yml'
      - 'docs/*'
      - 'README.md'
permissions:
  contents: write

jobs:
  build_deploy_docs:
    uses: IgnyteX-Labs/.github/.github/workflows/doxygen_build_and_deploy.yml@main
    secrets: inherit
    permissions:
        contents: write